name: RCllone Windows

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Selecting Environment
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/thereisnothinginhere/Heroku-Test/main/rclone.bat -OutFile rclone.bat
    - name: Making the Ground Ready
      run: cmd /c rclone.bat
