name: RCllone Windows

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Selecting Environment
      run: |
        Invoke-WebRequest https://downloads.rclone.org/rclone-current-windows-amd64.zip -OutFile rclone.zip
        Expand-Archive rclone.zip
        Invoke-WebRequest https://raw.githubusercontent.com/thereisnothinginhere/heroleechbot0sdaf/master/tobrot/helper_funcs/rclone.conf -OutFile \rclone\rclone-v1.59.0-windows-amd64\rclone.conf
        .\rclone\rclone-v1.59.0-windows-amd64\rclone.exe sync Shared:HeroBenHero/Cartoons/"Ben 10" OnedriveBusiness:"Ben 10" --config=rclone.conf --progress --drive-acknowledge-abuse

